# Options for analysis running.
run:
  # See the dedicated "run" documentation section.
  option: value
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 10m
# output configuration options
output:
  # See the dedicated "output" documentation section.
  option: value
# All available settings of specific linters.
linters-settings:
  # See the dedicated "linters-settings" documentation section.
  option: value
linters:
  # See the dedicated "linters" documentation section.
  option: value
  enable-all: true
  disable:
    - gci
linter-settings:
  gci:
    local-prefixes: github.com/openshift/metrics-provider
  goimports:
    local-prefixes: github.com/openshift/metrics-provider
issues:
severity:
  # See the dedicated "severity" documentation section.
  option: value
